title: BestHistory
description: Privacy-first Chrome browser history manager for searching old browser history, finding forgotten websites, and organizing history by website.
url: "https://besthistory.boxuezhiban.cn"
baseurl: ""
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
permalink: pretty
header_pages:
  - en/guides/index.md
  - LANGUAGES.md
